### ISSUE TITLE
Tentativa de uso

### ISSUE THREAD

**Issue by ElisonLima** [Antonio-Costa00/Alibaba-Auto-Quote-Request#6]
Tentei utilizar, porém, ele retorna este resultado:

```
 raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['dir_cont_link'] not found in axis"

```

**Comment by AntonioJCosta** [comment]
Boa noite! Peço perdão pelo erro. O erro esta ocorrendo pois a raspagem dos dados esta vindo vazia, e então ele não encontra a chave. Provavelmente o site mudou o layout. Irei adicionar uma tratativa para caso isso ocorra, e corrigir os novos valores para raspagem. Obrigado pelo apoio 😁

**Comment by ElisonLima** [comment]
Acredito que um Try/Except  já resolve :)

**Comment by AntonioJCosta** [comment]
O problema fo resolvido. Por favor, tente realizar um novo uso da aplicação. É normal que a aplicação demore um pouco para realizar a busca por novos fornecedores. Irei alterar a forma de requisição para uma chamada assincrona.

**Comment by ElisonLima** [comment]
Resolvido! Funcionou perfeitamente!
